#FROM      nginx
#RUN       rm -rf /usr/share/nginx/html/*
#RUN       echo Hello World >/usr/share/nginx/html/index.html
#CMD

FROM              centos:7
RUN               useradd roboshop
USER              roboshop

##ENTRYPOINT        ["sleep"]
##CMD               ["30"]
#ENV               URL=google.com


#FROM nginx
#COPY index.html /usr/share/nginx/html/index.html
