apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.16

---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: dummy
#  labels:
#    tier: frontend
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: dummy1
#  labels:
#    tier: frontend
#spec:
#  containers:
#    - name: nginx
#      image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-cip
spec:
  type: LoadBalancer
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


