apiVersion: v1
kind: Pod
metadata:
  name: sample3
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep", "1000"]
      envFrom:
        configMapRef:
          name: demo
      env:
        - name: SAMPLE_URL
          value: "google.com"
#        - name: SAMPLE_URL1
#          valueFrom:
#            configMapKeyRef:
#              name: demo
#              key: SAMPLE_URL1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
data:
  SAMPLE_URL1: "google1.com"
  URL1: example1.com
  URL2: example2.com

