apiVersion: v1
kind: Pod
metadata:
  name: sample3
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep", "1000"]
      env:
        - name: SAMPLE_URL
          value: "google.com"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
data:
  SAMPLE_URL1: "google1.com"

